version: '3.8'
services:
  dev-db: 
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - "./scripts/init:/docker-entrypoint-initdb.d"
      # - "./scripts/data.sql:/docker-entrypoint-initdb.d/init-data.sql"